services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dj_movierate_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=BelieveInSecurity12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    container_name: dj-movierate
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/dj-movie-rate
    depends_on:
      - db

volumes:
  postgres-data:
