# Generated by Django 5.0.6 on 2024-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_seasons',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
