# Generated by Django 5.0.6 on 2024-06-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production',
        ),
    ]
