# Generated by Django 5.0.6 on 2024-07-10 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_favmovie_moviereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favmovie',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_fav_movie_per_user'),
        ),
        migrations.AddConstraint(
            model_name='moviereview',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_review_movie_per_user'),
        ),
    ]
