# Generated by Django 5.0.6 on 2024-07-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_moviereview_rating_moviereview_impression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='memo',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='title',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
