# Generated by Django 5.0.6 on 2024-07-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_moviereview_memo_alter_moviereview_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moviereview',
            name='unique_review_movie_per_user',
        ),
    ]
