# Generated by Django 5.0.6 on 2024-07-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
