# Generated by Django 5.0.6 on 2024-07-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_moviereview_memo_alter_moviereview_title'),
        ('users', '0006_useractivity_activity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='action',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='object_id',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='active_favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.favmovie'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='active_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movierating'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='active_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.moviereview'),
        ),
    ]
