# Generated by Django 5.0.6 on 2024-07-23 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_moviereview_unique_review_movie_per_user'),
        ('users', '0007_rename_action_useractivity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='active_favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_favo_set', to='movies.favmovie'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='active_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_rating_set', to='movies.movierating'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='active_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_review_set', to='movies.moviereview'),
        ),
    ]
