# Generated by Django 5.0.6 on 2024-07-23 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_moviereview_unique_review_movie_per_user'),
        ('users', '0008_alter_useractivity_active_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='active_favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_favorite_set', to='movies.favmovie'),
        ),
    ]
