# Generated by Django 5.0.6 on 2024-07-23 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0009_alter_useractivity_active_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='active_favorite',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='active_rating',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='active_review',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
