# Generated by Django 5.0.6 on 2024-07-24 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_moviewatchlater_and_more'),
        ('users', '0012_alter_userfavoriteactivity_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchLaterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wl_activity_set', to='movies.favmovie')),
            ],
        ),
    ]
