# Generated by Django 5.0.6 on 2024-07-24 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userwatchlateractivity_wl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoriteactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_activity_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userratingactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_activity_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreviewactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_activity_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwatchlateractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wl_activity_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
