# Generated by Django 5.0.6 on 2024-07-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userfavoriteactivity_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150)),
                ('cca2', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='tuneduser',
            name='country',
        ),
        migrations.AlterField(
            model_name='tuneduser',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
