# Generated by Django 5.0.6 on 2024-07-27 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_country_remove_tuneduser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuneduser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
    ]
