# Generated by Django 5.0.6 on 2024-07-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tuneduser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuneduser',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
    ]
