# Generated by Django 5.0.6 on 2024-07-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_tuneduser_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-pk']},
        ),
    ]
