# Generated by Django 5.0.6 on 2024-07-28 02:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuneduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.get_upload_path),
        ),
    ]
